Config = {}

Config.ScanDistance = 30.0 -- Distance
Config.ScanKey = 38        -- Button (38 = E)

Config.Jobs = {
    "police",  
    "sheriff", 
}

Config.VehicleClass = {
    ['A'] = {
        { name = "Rhinehart",                 model = "rhinehart" },
        { name = "Lampadati cinquemila",      model = "cinquemila" },
        { name = "Annis Kawaii",              model = "kawaii" },
        { name = "Pegassi Infernus Classic",  model = "infernus", },
        { name = "Benefactor Feltzer",        model = "feltzer2", },
        { name = "Raiden",                    model = "raiden" },
        { name = "Bravado Verlierer",         model = "verlierer2" },
        { name = "Vectre",                    model = "vectre" },
        { name = "Dinka RT-3000",             model = "rt3000" },
        { name = "Toundra Panthere",          model = "panthere" },
        { name = "Emperor Sheavas",           model = "sheavas" },
        { name = "FR36",                      model = "fr36" },
        { name = "Voltic",                    model = "voltic" },
        { name = "HR Spec",                   model = "hrspec" },
        { name = "Dewbauchee Massacro",       model = "massacro" },
        { name = "Vapid Bullet",              model = "bullet", },
        { name = "Grotti Cheetah Classic",    model = "cheetah2", },
        { name = "Turismo Classic",           model = "turismo2", },
        { name = "Maxwell Sidewinder",        model = "gbsidewinder" },
        { name = "Lampadati Felon GT",        model = "felon2" },
        { name = "Karin S14",                 model = "sultan3" },
        { name = "Annis ZR350",               model = "zr350" },
        { name = "Emperor Vectre",            model = "vectre" },
        { name = "Annis Elegy ",              model = "elegy2" },
        { name = "Annis Elegy Retro",         model = "elegy" },
        { name = "Lampadati Komoda",          model = "komoda" },
        { name = "Albany VSTR",               model = "vstr" },
        { name = "Karin Kuruma",              model = "kuruma" },
        { name = "Dewbauchee Specter Custom", model = "specter2" },
        { name = "Annis Elegy RH4",           model = "rh4" },
        { name = "Obey Tailgater",            model = "tailgater2" },
        { name = "Karin Sigma Classic",       model = "sigma2" },
        { name = "Obey 9F",                   model = "ninef" },
        { name = "Obey 9F Cabrio",            model = "ninef2" },
        { name = "Bravado Banshee",           model = "banshee" },
        { name = "Invetero Coquette",         model = "coquette" },
        { name = "Obey 8F Drafter",           model = "drafter" },
        { name = "Vapid Dominator ASP",       model = "dominator7" },
        { name = "Annis S230",                model = "s230" }, --
        { name = "Karin Calico",              model = "calico" },
        { name = "Ocelot Lynx",               model = "lynx" },
        { name = "Ocelot Jugular",            model = "jugular" },
        { name = "Grotti Carbonizzare",       model = "carbonizzare" },
        { name = "Pfister Comet",             model = "comet2" },
        { name = "Pfister Comet SR",          model = "comet5" },
        { name = "Lampadati Furore GT",       model = "furoregt" },
        { name = "Ubermacht Sentinel GTS",    model = "sentinel5" },
        { name = "Dinka Jester",              model = "jester" },
        { name = "Dinka Jester Classic",      model = "jester3" },
        { name = "Bravado Buffalo STX",       model = "buffalo4" },
        { name = "Ocelot Pariah",             model = "pariah" },
        { name = "Ocelot Locust",             model = "locust" },
        { name = "Bravado Gauntlet Hellfire", model = "gauntlet4" },
        { name = "Enus Paragon",              model = "paragon" },
        { name = "Karin Sultan Classic",      model = "sultan2" },
        { name = "Pegassi Torero",            model = "torero" },
        { name = "Vapid Dominator GTX",       model = "dominator3" },
        { name = "Dewbauchee Rapid GT",       model = "rapidgt" }, 
        { name = "Dewbauchee Specter",        model = "specter" }, 
        { name = "Ocelot F620",               model = "f620" },
        { name = "Dewbauchee Exemplar",       model = "exemplar" },
    },
    ['B'] = {
        { name = "Bravado Gresley STX", model = "gbgresleystx" },
        { name = "Dinka Kanjo SJ",      model = "kanjosj" },
        { name = "Lampadati Komoda GT", model = "gbkomodagt" },
        { name = "Schlagen SP",         model = "gbschlagensp", },
        { name = "Karin Sultan",        model = "sultan" },
        { name = "Dominator 645",       model = "DOM645" },
        { name = "Karin CNF",           model = "gstcnf1" },
        { name = "Declasse Tahoma GT",  model = "gbtahomagt" },
        { name = "Dewbauchee Seven-70", model = "seven70" },
        { name = "Imponte Nightshade",  model = "nightshade" },
        { name = "Willard Paradox",     model = "paradox" },
        { name = "Khamelion",           model = "khamelion" },
        { name = "Karin Futo GTX",      model = "futo2" },
        { name = "Dinka Sugoi",         model = "sugoi" },
        { name = "Weeny Issi Rally",    model = "issi8" },
        { name = "Ubermacht Oracle",    model = "oracle" },
        { name = "Ubermacht Oracle XS", model = "oracle2" },
        { name = "Lampadati Felon",     model = "felon" },
        { name = "Obey DD",             model = "doubled" },
        { name = "Vapid Dominator",     model = "dominator" },
        { name = "Vulcar Starlight",    model = "gbstarlight" },
    },
    ['C'] = {
        { name = "Grotti Stinger",             model = "stinger" },
        { name = "Karin 190z",                 model = "z190" },
        { name = "Bravado Gauntlet",           model = "gauntlet" },
        { name = "Bravado Buffalo S",          model = "buffalo2" },
        { name = "Shyster Fusilade",           model = "fusilade" },
        { name = "Zirconium Stratum Custom",   model = "stratumc" },
        { name = "Grotti Bestia GTS",          model = "bestiagts" },
        { name = "Annis ZR250",                model = "zr250" },
        { name = "Karin Previon ",             model = "previon" },
        { name = "Benefactor Schrauber",       model = "gbschrauber" },
        { name = "Weeny Issi Metro",           model = "gbissimetro" },
        { name = "Benefactor Schwartzer",      model = "schwarzer" },
        { name = "Benefactor Vorschlaghammer", model = "vorschlaghammer" },
        { name = "Bordeaux Vivant GRB",        model = "gbvivantgrb" },
        { name = "Weeny Issi",                 model = "issi2" },
        { name = "Dundeary Admiral",           model = "gbadmiral" },
        { name = "Dundeary Hades",             model = "gbhades" },
        { name = "Declasse Rhapsody",          model = "rhapsody" },
        { name = "Bordeaux Vivant",            model = "gbvivant" },
        { name = "Obey I-Asterope2",           model = "asterope2" },
        { name = "Declasse Impaler LE",        model = "gbimpaler" },
    },
    ['D'] = {
        { name = "Ubermacht Sentinel Classic",    model = "sentinel3" },
        { name = "Ubermacht Sentinel Classic WB", model = "sentinel4" },
        { name = "Ubermacht Sentinel",            model = "sentinel" },
        { name = "Ubermacht Sentinel XS",         model = "sentinel2" },
        { name = "Ubermacht Zion",                model = "zion" },
        { name = "Ubermacht Zion Cabrio",         model = "zion2" },
        { name = "Vapid Ellie",                   model = "ellie" },
        { name = "Declasse Vamos",                model = "vamos" },
        { name = "Imponte Ruiner",                model = "ruiner" },
        { name = "Bravado Buffalo",               model = "buffalo" },
        { name = "Vapid Contender Custom",        model = "contenderc" },
        { name = "Ubermacht Rebla GTS",           model = "rebla" },
        { name = "Karin Asterope",                model = "asterope" },
        { name = "Dinka Blista",                  model = "blista" },
        { name = "Dinka Blista Compact",          model = "blista2" },
        { name = "Lampadati Michelli GT",         model = "michelli" },
        { name = "Dinka Kanjo",                   model = "kanjo" },
        { name = "Dinka Postlude",                model = "postlude" },
        { name = "BF Weevil",                     model = "weevil" },
        { name = "BF Injection",                  model = "bfinjection" },
        { name = "Grotti Brioso F",               model = "gbbriosof" },
        { name = "Rune Cheburek",                 model = "cheburek" },
        { name = "Karin Dilettante",              model = "dilettante" },
        { name = "Bordeaux Arias",                model = "arias" },
        { name = "Grotti Brioso Classic",         model = "brioso3" },
        { name = "Brioso Classic",                model = "brioso2" },
        { name = "Grotti Brioso R/A",             model = "brioso" },
        { name = "BF Club",                       model = "club" },
        { name = "Albany Primo",                  model = "primo" },
        { name = "Albany Primo Custom",           model = "primo2" },
        { name = "Benefactor Panto",              model = "panto" },
        { name = "Maxwell Asbo",                  model = "asbo" },
        { name = "Declasse Asea",                 model = "asea" },
        { name = "Karin Intruder",                model = "intruder" },
        { name = "Vulcar Fagaloa",                model = "fagaloa" },
        { name = "Obey Tailgater",                model = "tailgater" },


    },
    ['S'] = {
        { name = "6STR Schwartzer",            model = "schwarzer2" },
        { name = "Bravado Gauntlet STR",       model = "gauntlet6str" },
        { name = "Bravado Gauntlet S",         model = "gauntlets" },
        { name = "Bravado Buffalo New",        model = "buffalo5" },
        { name = "BF Club XR",                 model = "gbclubxr" },
        { name = "Dinka Jester RR2",           model = "jester5" },
        { name = "Dinka Jester RR",            model = "jester4" },
        { name = "Ubermacht Cypher",           model = "cypher" },
        { name = "Lampadati Komoda FR",        model = "komodafr" },
        { name = "Pfister Comet Retro",        model = "comet3" },
        { name = "Pfister Comet S2",           model = "comet6" },
        { name = "Vapid Dominator Cabrio",     model = "dominator9" },
        { name = "Obey Argento",               model = "argento" },
        { name = "Karin Asterope RS",          model = "asteropers" },
        { name = "Declasse Vigero 2",          model = "vigero2" },
        { name = "Declasse Vigero Cabrio",     model = "vigero3" },
        { name = "Annis ZR380 STR",            model = "zr3806str" },
        { name = "Declasse Vigero 22",         model = "vigeronew" },
        { name = "Pfister Comet CL",           model = "gbcometcl" },
        { name = "Karin Sultan RSX",           model = "gbsultanrsx" },
        { name = "Karin Dominator GSX",        model = "gbdominatorgsx" },
        { name = "Annis Elegy Widebody",       model = "rh82" },
        { name = "Ubermach Sentinel",          model = "sentinelsg4" },
        { name = "Obey Drafter Custom",        model = "draftgpr" },
        { name = "Pegassi Toros",              model = "toros" },
        { name = "Maibatsu A80",               model = "penumbra2" },
        { name = "Dinka Nexus NA1",            model = "nexus" },
        { name = "Annis ZR390 ",               model = "zr390" },
        { name = "Annis Remus",                model = "remus" },
        { name = "Annis Euros",                model = "euros" },
        { name = "Karin Sultan RS",            model = "sultanrs" },
        { name = "Emperor Ronin",              model = "gbronin" },
        { name = "Obey 10F",                   model = "tenf" },
        { name = "Obey 10F WB",                model = "tenf2" },
        { name = "Dinka Nexus RR",             model = "gbnexusrr" },
        { name = "Obey Argento RS6",           model = "GBARGENTO7F" },
        { name = "Obey Argento 7F",            model = "argento7fs" },
        { name = "Bravado Banshee S",          model = "gbbanshees" },
        { name = "Pfister Comet S1 Turbo",     model = "gbcomets1t" },
        { name = "Pfister Comet S2R",          model = "GBCOMETS2R" },
        { name = "Pfister Comet S2R Cabrio",   model = "GBCOMETS2RC" },
        { name = "Ubermach Sentinel GTS",      model = "gbsentinelgts" },
        { name = "Ocelot Lynx WB",             model = "lynxgpr" },
        { name = "Jester RR Custom",           model = "jestgpr" },
        { name = "Toundra Raidillon",          model = "gbraidillon" },
        { name = "Obey TenF Cabrio",           model = "gbtenfr" },
        { name = "Karin Mogul RS",             model = "gbmogulrs" },
        { name = "Deuwbauchee Solace",         model = "gbsolace" },
        { name = "Infernus Classic",           model = "infernus2" },
        { name = "Grotti Stinger TT",          model = "stingertt" },
        { name = "Enus Deity",                 model = "deity" },
        { name = "Grotti Itali RSX",           model = "italirsx", },
        { name = "Pegassi Ignus",              model = "ignus", },
        { name = "Grotti Itali GTO",           model = "italigto", },
        { name = "Schlagen GT",                model = "schlagen", },
        { name = "Schlagen Roadster",          model = "gbschlagenr", },
        { name = "Itali RSX",                  model = "italirsx", },
        { name = "Turismo Classic",            model = "turismoc", },
        { name = "Turismo S",                  model = "turismos", },
        { name = "Turismo 7 ",                 model = "turismo7", },
        { name = "Turismo R ",                 model = "turismor", },
        { name = "Grotti Cheetah",             model = "cheetah", },
        { name = "Overflod Entity XF",         model = "entityxf", },
        { name = "Overflod Entity XXR",        model = "entity2", },
        { name = "Overflod Entity MT",         model = "entity3", },
        { name = "Progen Emerus",              model = "emerus", },
        { name = "Vapid FMJ",                  model = "fmj", },
        { name = "Grotti Furia",               model = "furia", },
        { name = "Progen GP1",                 model = "gp1", },
        { name = "Itali GTB",                  model = "italigtb", },
        { name = "Benefactor Krieger",         model = "krieger", },
        { name = "Truffade Nero",              model = "nero", },
        { name = "Truffade Nero Custom",       model = "nero2", },
        { name = "Pegassi Osiris",             model = "osiris", },
        { name = "Pegassi Reaper",             model = "reaper", },
        { name = "Ubermach SC1",               model = "sc1", },
        { name = "Progen T20",                 model = "t20", },
        { name = "Pegassi Tempesta",           model = "tempesta", },
        { name = "Truffade Thrax",             model = "thrax", },
        { name = "Lampadati Tigon",            model = "tigon", },
        { name = "Overflod Tyrant",            model = "tyrant", },
        { name = "Ocelot XA-21",               model = "xa21", },
        { name = "Pegassi Vacca",              model = "vacca", },
        { name = "Coquette D10 Custom",        model = "coquette4c", },
        { name = "Grotti Itali GTON",          model = "italigton", },
        { name = "Schlagen STR",               model = "schlagenstr", },
        { name = "Grotti Itali GTS",           model = "italigts", },
        { name = "Grotti Itali GTR",           model = "italigtr", },
        { name = "Deimos",                     model = "deimos", },
        { name = "Obey Omnis E-GT",            model = "omnisegt", },
        { name = "Growler",                    model = "growler" },
        { name = "Pegassi Torero Classic",     model = "torero2" },
        { name = "Roxanne S15",                model = "roxanne" },
        { name = "Vysser Neo",                 model = "neo" },
        { name = "Obey NineR",                 model = "niner" },
        { name = "Maibatsu Vincent",           model = "vincent2" },
        { name = "Annis Remus",                model = "remustwo" },
        { name = "adder",                      model = "adder" },
        { name = "Grotti Turismo-3",           model = "turismo3" },
        { name = "Zentorno",                   model = "zentorno" },
        { name = "Penetrator",                 model = "penetrator" },
        { name = "Grotti Itali GTB2",          model = "italigtb2" },
        { name = "Tyrus",                      model = "tyrus" },
        { name = "Zorrusso",                   model = "zorrusso" },
        { name = "Champion",                   model = "champion" },
        { name = "Zeno",                       model = "zeno" },
        { name = "Super GTS",                  model = "supergts" },
        { name = "Tempesta EVO",               model = "tempestaevo" },
        { name = "Meteor",                     model = "meteor" },
        { name = "Pentro",                     model = "pentro" },
        { name = "Pentro GPR",                 model = "pentrogpr" },
        { name = "Auroras",                    model = "auroras" },
        { name = "Annis AS-ZR350",             model = "as_zr350" },
        { name = "Vapid Dominator TF",         model = "tfdominator" },
        { name = "Schlagen SL",                model = "la_schlagensl", },
        { name = "s96",                        model = "s96" },
        { name = "Pfister Comet H4R",          model = "H4RxST2" },
        { name = "Pfister Comet 811S2",        model = "GB811S2" },
        { name = "Annis ZR380-S",              model = "ZR380S" },
        { name = "Enus Paragon XR",            model = "paragonxr" },
        { name = "Dewbauchee Solace Cabrio",   model = "gbsolacev" },
        { name = "Grotti Turismo GTS",         model = "gbturismogts" },
        { name = "Enus Sapphire",              model = "gbsapphire" },
        { name = "Pfister Neon ",              model = "neon" },
        { name = "Pfister Neon CT",            model = "gbneonct" },
        { name = "Vesper",                     model = "VESPER" },
        { name = "Pfister Comet S2 Cabrio",    model = "comet7" },
        { name = "Lampadati Corsita",          model = "corsita" },
        { name = "Pfister 811",                model = "pfister811" },
        { name = "Karin Venosso",              model = "gstsh51" },
        { name = "Nio-2",                      model = "gstnio2" },
        { name = "Ter-1",                      model = "gstter1" },
        { name = "Declasse Tampa CTX",         model = "gsttam1" },
        { name = "TNS-1",                      model = "GSTNS1" },
        { name = "GSTCNS1",                    model = "GSTCNS1" },
        { name = "gstcs24",                    model = "gstcs24" },
        { name = "gstrh5s1",                   model = "gstrh5s1" },
        { name = "gstsg71",                    model = "gstsg71" },
        { name = "gstsg71c",                   model = "gstsg71c" },
        { name = "konnen2",                    model = "konnen2" },
        { name = "Bravado Buffalo GTX",        model = "buffalogtx" },
        { name = "Annis Elegy RH9",            model = "elegyrh9" },
        { name = "Bravado Gauntlet GT",        model = "gauntletgt" },
        { name = "Ubermacht Nocturne",         model = "nocturne" },
        { name = "Benefactor Exelion",         model = "exelion" },
        { name = "Ubermacht Sentinel MK4 GTR", model = "sentinelmk4gtr" },
        { name = "Ubermacht Sentinel MK4 ",    model = "sentinelmk4" },
        { name = "Karin Sultan RSV8",          model = "sultanrsv8" },
        { name = "Benefactor Schwartzer S",    model = "gbschwartzers" },
        { name = "Benefactor Harmann",         model = "gbharmann" },
        { name = "Bollokan Iris Z",            model = "gbirisz" },
        { name = "Ubermach Oracle SLE ",       model = "oracxsle" },
        { name = "Annis Elegy RH6",            model = "elegyrh6" },
        { name = "Annis Elegy RH7",            model = "elegyrh7" },
        { name = "Annis Elegy RH7-2",          model = "ELEGYRH72" },
        { name = "Progen Emerus SB1",          model = "gbemerussb1", },
        { name = "Grotti Milano GTS",          model = "gbmilano", },
        { name = "Progen TR3-S",               model = "gbtr3s", },
        { name = "Pegassi Prospero",           model = "GBPROSPERO", },
        { name = "Pfister 811 S2",             model = "GB811S2", },
        { name = "Coquette D10",               model = "coquette4", },
        { name = "Annis ZR-GPR",               model = "zrgpr" },
        { name = "Pfister Comet Callista",     model = "callista" },
        { name = "Annis Elegy Heritage",       model = "elegyheritage" },
        { name = "Annis Elegy X",              model = "elegyx" },
        { name = "Cypher-CT",                  model = "cypherct" },
        { name = "Hachura-C",                  model = "hachurac" },
        { name = "Sunrise",                    model = "sunrise1" },
        { name = "Benefactor Dubsta 22",       model = "dubsta22" },
        { name = "Annis ZR150",                model = "zr150" },
        { name = "Annis Mochi",                model = "gbmochi" },
        { name = "Maibatsu Archer Pro",        model = "gbarcherpro2" },
        { name = "Grotti Cheetah S",           model = "gbcheetahs" },
        { name = "Annis Rumina",               model = "gbrumina" },
        { name = "Grotti Mugello",             model = "gbmugello" },
        { name = "Dominator Classic Custom",   model = "domc" },     
        { name = "Ubermach Vorstand",          model = "vorstand" }, 
        { name = "Argento 7fs",                model = "gbargento7fs" },
        { name = "Cypher GTS",                 model = "gbcyphergts" },
        { name = "Romulus",                    model = "gbromulus" },
        { name = "EDW XR4",                    model = "edw-xr4" },
        { name = "EDW XR5",                    model = "edw-xr5" },
    },
    ['M'] = {
        { name = "Maibatsu Manchez Scout",    model = "manchez2" },
        { name = "Dinka Akuma",               model = "akuma" },
        { name = "Pegassi Bati",              model = "bati" },
        { name = "Pegassi Bati 801RR",        model = "bati2" },
        { name = "Nagasaki Carbon RS",        model = "carbonrs" },
        { name = "Shitzu Defiler",            model = "defiler" },
        { name = "Dinka Double-T",            model = "double" },
        { name = "Shitzu Hakuchou",           model = "hakuchou" },
        { name = "Shitzu Hakuchou Drag",      model = "hakuchou2" },
        { name = "Pegassi Faggio",            model = "faggio" },
        { name = "Pegassi Faggio Sport",      model = "faggio2" },
        { name = "Pegassi Faggio Custom",     model = "faggio3" },
        { name = "LCC Avarus",                model = "avarus" },
        { name = "Western Daemon",            model = "daemon" },
        { name = "Western Daemon Custom",     model = "daemon2" },
        { name = "Western Gargoyle",          model = "gargoyle" },
        { name = "LCC Hexer",                 model = "hexer" },
        { name = "LCC Innovation",            model = "innovation" },
        { name = "Western Nightblade",        model = "nightblade" },
        { name = "Western Ratbike",           model = "ratbike" },
        { name = "LCC Sanctus",               model = "sanctus" },
        { name = "Western Zombie Chopper",    model = "zombiea" },
        { name = "Western Zombie Bobber",     model = "zombieb" },
        { name = "Nagasaki BF400",            model = "bf400" },
        { name = "Dinka Enduro",              model = "enduro" },
        { name = "Maibatsu Manchez",          model = "manchez" },
        { name = "Principe Nemesis",          model = "nemesis" },
        { name = "Shitzu PCJ 600",            model = "pcj" },
        { name = "Western Bagger",            model = "bagger" },
        { name = "Nagasaki Chimera",          model = "chimera" },
        { name = "Western Cliffhanger",       model = "cliffhanger" },
        { name = "Principe Diablous",         model = "diablous" },
        { name = "Principe Diablous Custom",  model = "diablous2" },
        { name = "Pegassi Esskey",            model = "esskey" },
        { name = "Western Sovereign",         model = "sovereign" },
        { name = "Pegassi Bati 901",          model = "bati901" },
        { name = "Western Big Dude",          model = "bigdude" },
        { name = "Ubermacht Kampfer",         model = "kampfer" },
        { name = "Western Krust",             model = "krust" },
        { name = "Western Nightblade Custom", model = "nightblade2" },
        { name = "Western Salt Flat",         model = "saltflat" },
        { name = "Nagasaki Shinobio",         model = "shinobio" },
        { name = "Nagasaki Shinobi",          model = "shinobi" },
        { name = "Western Slave",             model = "slave" },
        { name = "Western Sombrero",          model = "sombrero" },
        { name = "Dinka Ventoso",             model = "ventoso" },
        { name = "Nagasaki Blazer",           model = "blazer" },
        { name = "Nagasaki Street Blazer",    model = "blazer4" },
        { name = "Nagasaki Aqua Blazer",      model = "blazer5" },
        { name = "Nagasaki Custom Blazer",    model = "blazer3" },
        { name = "Pegassi Bati 701",          model = "bati701" },
        { name = "Western Reever",            model = "reever" },
        { name = "Nagasaki Kunoichi",         model = "kunoichi" },


        -- { name = "",                          model = "" },
        -- { name = "",                          model = "" },
        -- { name = "",                          model = "" },
        -- { name = "",                          model = "" },
    },
}
